[package]
name = "web-terminal"
version = "0.1.0"
edition = "2021"


[dependencies]
ws = { git = "https://gitee.com/luoshuqi/ws" }
tokio = { version = "1", features = ["full"] }
nix = "0"
log = "0"
env_logger = "0"
structopt = "0"
base64 = "0"
pam-client = "0"